jobs/urls.py
from django.urls import re_path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.static import static
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.views.decorators.csrf import csrf_exempt
from graphene_file_upload.django import FileUploadGraphQLView

from jobs.sitemaps import Sitemaps, StaticViewSitemap
from resume_cv.views import load_builder, update_builder

schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(path("", include("jobsapp.urls")),
                              path("", include("accounts.urls")),
                              path("", include("resume_cv.urls")),
                              )

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    re_path(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("templates/load-builder/<id>", load_builder, name="resume-cv.load.builder"),
    path("templates/update-builder/<id>", csrf_exempt(update_builder), name="resume-cv.update.builder"),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    # url(r"^(?P<url>.*/)$", flatpages_views.flatpage),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
    path("graphql/", csrf_exempt(FileUploadGraphQLView.as_view(graphiql=True))),
]

if settings.ENABLE_PROMETHEUS:
    urlpatterns.append(path("", include('django_prometheus.urls')))

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resume_cv/urls.py
from django.urls import path

from .views import (
    TemplateListView,
    ResumeCVCreateView,
    resume_builder,
    load_builder,
)

app_name = "resume_cv"

urlpatterns = [
    path("templates", TemplateListView.as_view(), name="templates"),
    path("resume-cv/create", ResumeCVCreateView.as_view(), name="create"),
    path("templates/builder/<code>", resume_builder, name="builder"),
]

templates/resumes/builder.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <title>{{ resume.name }}</title>
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet"
          href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <link rel="stylesheet" href="{% static 'css/builder.css' %}">
    <link rel="stylesheet" href="{% static 'css/customize.css' %}">
    <style>
        #resumecv-content-top {
            background-color: red;
        }
    </style>
</head>

<body>
<div id="mobileAlert">
    <div class="message">
        <h3>Builder doesn't work on mobile</h3>
        <a href="#">Back</a>
    </div>
</div>
<!-- The Modal -->
<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h2>Select a template</h2>
            <span class="close">&times;</span>
        </div>
        <div class="row">
            {% for template in templates %}
                <div class="column">
                    <div class="card card-template" data-templateid="{{ template.id }}">
                        <img src="{{ template.thumbnail.url }}" alt="{{ template.name }}"
                             data-was-processed="true" class=""/>
                        <div class="container">
                            <h4><b>{{ template.name }}</b></h4>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<div id="loadingMessage">
    <div class="lds-ring">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<div id="gjs"></div>

<script type="text/javascript">
    var _token = '{{ token }}';
    var upload_Image = 'uploadimage_url';
    var url_load_template = "";
    var url_default_css_template = '{% static 'css/font-awesome.css' %}';
    var urlStore = '{% url 'resume-cv.update.builder' resume.id %}';
    var urlLoad = '{% url 'resume-cv.load.builder' resume.id %}';
    var back_button_url = "{% url 'resume_cv:templates' %}";
    var exportPDF_url = "";

    var images_url = ['{% static 'img/1875187.jpg' %}'];
    var all_fonts = ['Arial', 'Verdana', 'Helvetica', 'Tahoma', 'Trebuchet MS', 'Times New Roman', 'Georgia', 'Garamond', 'Courier New', 'Brush Script MT'];
    var langs = {
        "fontFamily": "FONT FAMILY",
        "changeTemplates": "Change Templates",
        "exportPdf": "Download PDF",
    };
    var config = {
        all_icons: ["fab fa-500px", "fab fa-accessible-icon", "fab fa-accusoft", "fab fa-acquisitions-incorporated", "fas fa-ad", "fas fa-address-book", "far fa-address-book", "fas fa-address-card"],
    };
    var all_icons = ["fab fa-500px", "fab fa-accessible-icon", "fab fa-accusoft", "fab fa-acquisitions-incorporated", "fas fa-ad", "fas fa-address-book", "far fa-address-book", "fas fa-address-card"];

</script>
<script src="{% static 'js/builder.js' %}"></script>
<script src="{% static 'js/preset.js' %}"></script>
<script src="{% static 'js/custom-builder.js' %}"></script>
</body>

</html>

templates/resumes/templates.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All templates
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/templates.css' %}"/>
{% endblock %}

{% block content %}

    <section class="mt-4">
        <div class="container">
            <h2 class="text-center">Choose a template for your Resume/CV</h2>
            <a href="{% url 'resume_cv:templates' %}" class="btn btn-sm btn-danger">All Templates</a>
            {% for category in categories %}
                <a href="{% url 'resume_cv:templates' %}" class="btn btn-sm btn-success">{{ category.name }}</a>
            {% endfor %}

            <div class="row mt-2">
                {% for template in templates %}
                    <div class="col-md-4">
                        <div class="clearfix blog-bottom blog blogitemlarge">
                            <a href="#" data-id="{{ template.id }}" data-toggle="modal" data-target="#createModal" title="Resume 8"
                               class="btn_builder_template image-blog date clearfix">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwhqZsr5q4Dz-ecvcVg_9WzU0VsmEw6l6pYYaq9RdWKw&s"
                                     alt="{{ template.name }}"
                                     data-was-processed="true" class="">
                                <span class="post-date badge badge-success"> Free</span>
                            </a>
                            <div class="content_blog clearfix flex flex-column flex-lg-row">
                                <div class="p-1">
                                    {{ template.name }}
                                </div>
                                <div class="d-flex pt-1">
                                    <a href="#" class="btn btn-sm btn-primary mr-2 btn_builder_template" data-id="{{ template.id }}"
                                       data-toggle="modal" data-target="#createModal">Builder</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">New Resumecv</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="" action="{% url 'resume_cv:create' %}" method="post">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="number" class="form-control" name="template" hidden required
                                       id="template_id_builder">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" name="name" required="" id="page-name">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary btn-sm" id="saveandbuilder">Save & Builder
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}